---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-ordering-service
  labels:
    app: online-ordering-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-ordering-service
  template:
    metadata:
      labels:
        app: online-ordering-service
    spec:
      containers:
        - name: online-ordering-service
          image: omarhosny102/online-ordering-service:latest
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: host
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: db-name
            - name: DATABASE_PORT
              value: "3300"
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: online-ordering-service-service
  labels:
    app: online-ordering-service-service
spec:
  type: ClusterIP
  selector:
    app: online-ordering-service
  ports:
    - port: 3200
      targetPort: 8080
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-ordering-service-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: api.online-ordering-service.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: online-ordering-service-service
                port:
                  number: 3200
